import type { Driver } from './types';

export const mockDrivers: Driver[] = [
  {
    _id: '1',
    name: 'Ranj Karem',
    phone: '+9647701234567',
    email: 'ranj.karem@example.com',
    licenseNumber: 'SUL12345',
    vehicleType: 'taxi',
    vehicleModel: 'Toyota Corolla 2022',
    licensePlate: '2345 SUL',
    vehicleImage: 'https://placehold.co/300x200.png',
    isAvailable: true,
    location: {
      type: 'Point',
      coordinates: [45.4333, 35.5642], // [lng, lat]
    },
    rating: 4.8,
    isApproved: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '2',
    name: 'Shara Hawrami',
    phone: '+9647509876543',
    email: 'shara.hawrami@example.com',
    licenseNumber: 'SUL54321',
    vehicleType: 'bus',
    vehicleModel: 'Mercedes-Benz Tourismo',
    licensePlate: '9876 SUL',
    vehicleImage: 'https://placehold.co/300x200.png',
    isAvailable: true,
    location: {
      type: 'Point',
      coordinates: [45.4411, 35.5589],
    },
    rating: 4.5,
    isApproved: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '3',
    name: 'Aram Gulli',
    phone: '+9647712345678',
    email: 'aram.gulli@example.com',
    licenseNumber: 'SUL67890',
    vehicleType: 'truck',
    vehicleModel: 'Volvo FH16',
    licensePlate: '5432 SUL',
    vehicleImage: 'https://placehold.co/300x200.png',
    isAvailable: true,
    location: {
      type: 'Point',
      coordinates: [45.4195, 35.5691],
    },
    rating: 4.9,
    isApproved: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '4',
    name: 'Naza Qadir',
    phone: '+9647501122334',
    email: 'naza.qadir@example.com',
    licenseNumber: 'SUL11223',
    vehicleType: 'vegetable',
    vehicleModel: 'Kia Bongo',
    licensePlate: '1122 SUL',
    vehicleImage: 'https://placehold.co/300x200.png',
    isAvailable: true,
    location: {
      type: 'Point',
      coordinates: [45.4500, 35.5500],
    },
    rating: 4.2,
    isApproved: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '5',
    name: 'Hemin Ali',
    phone: '+9647705566778',
    email: 'hemin.ali@example.com',
    licenseNumber: 'SUL55667',
    vehicleType: 'motorcycle',
    vehicleModel: 'Honda CBR500R',
    licensePlate: '8877 SUL',
    vehicleImage: 'https://placehold.co/300x200.png',
    isAvailable: true,
    location: {
      type: 'Point',
      coordinates: [45.4250, 35.5750],
    },
    rating: 5.0,
    isApproved: false,
    createdAt: new Date().toISOString(),
  },
   {
    _id: '6',
    name: 'Bahar Murad',
    phone: '+9647701112222',
    email: 'bahar.murad@example.com',
    licenseNumber: 'SUL88888',
    vehicleType: 'taxi',
    vehicleModel: 'Hyundai Elantra 2021',
    licensePlate: '1212 SUL',
    vehicleImage: 'https://placehold.co/300x200.png',
    isAvailable: false,
    location: {
      type: 'Point',
      coordinates: [45.4300, 35.5500],
    },
    rating: 4.6,
    isApproved: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '7',
    name: 'Kamaran Jalal',
    phone: '+9647703334444',
    email: 'kamaran.jalal@example.com',
    licenseNumber: 'SUL77777',
    vehicleType: 'gas',
    vehicleModel: 'Gas Tanker Truck',
    licensePlate: '4444 SUL',
    vehicleImage: 'https://placehold.co/300x200.png',
    isAvailable: true,
    location: {
      type: 'Point',
      coordinates: [45.4000, 35.5800],
    },
    rating: 4.7,
    isApproved: true,
    createdAt: new Date().toISOString(),
  },
    {
    _id: '8',
    name: 'Sazan Barzinji',
    phone: '+9647505556666',
    email: 'sazan.barzinji@example.com',
    licenseNumber: 'SUL66666',
    vehicleType: 'flat_recovery',
    vehicleModel: 'Ford F-450 Tow Truck',
    licensePlate: '6666 SUL',
    vehicleImage: 'https://placehold.co/300x200.png',
    isAvailable: true,
    location: {
      type: 'Point',
      coordinates: [45.4600, 35.5700],
    },
    rating: 4.9,
    isApproved: true,
    createdAt: new Date().toISOString(),
  },
];
